### ISSUE TITLE
N official integration

### ISSUE THREAD

**Issue by farfromrefug** [klippa-app/nativescript-http#10]
We just discovered your plugin and it is pretty awesome!
Could become an official N plugin (as moving to @nativescript npm scope) if you are interested.

I think we could make it even better though:
* splitting the websocket implementation into a "subplugin" to prevent too many native deps. like nativescript-http-websocket or something which would depend on this one. No real consequence on android but on ios it would remove the requirement for `SocketRocket`
* maybe even do the same thing for `TrustKit` ?
* support forcing the okhttp version the same way as done through N . I did that for nativescript-https https://github.com/EddyVerbruggen/nativescript-https/blob/master/src/platforms/android/include.gradle#L2

Let us know what you think about that opportunity

**Comment by jerbob92** [comment]
Sounds good to me! I agree that having less dependencies would be better :+1: 
Ability to configure the okhttp version sounds good to me, I already provide a solution for that in the docs using `resolutionStrategy.force`, but implementing it the same way as other plugins sounds like a better plan. 

I'm also pretty active on the Slack (name: Jeroen Bobbeldijk), if you want to discuss more :)

**Comment by NathanWalker** [comment]
Excellent @jerbob92 really appreciate this plugin. We will reach out to you regarding this in the coming weeks as we strengthen core as well as refactor various parts for optimizations.
