### ISSUE TITLE
[FR] run big opps in threads

### ISSUE THREAD

**Issue by farfromrefug** [klippa-app/nativescript-http#14]
When getting the repsonse either in json or writting to a file, it can often be very long and thus will blockntr main thread.
Would you consider running those in a thread? 
I implemented that in https plugin here https://github.com/EddyVerbruggen/nativescript-https/blob/master/src/platforms/android/java/com/nativescript/https/OkHttpResponse.java

**Comment by jerbob92** [comment]
I'm open to it :+1: 

However, there always has to happen a transition between Java String to JavaScript string, so question is whether that is faster than doing the toString from JavaScript.
