### ISSUE TITLE
Cannot find runtime for instance=com.tns.gen.okhttp3.Callback

### ISSUE THREAD

**Issue by LiamMcCallum** [klippa-app/nativescript-http#15]
Hello,

We run an Android TV app that is designed to be running for days. Unfortunately at least once a day we're seeing the following crash. It's reported on MS App Center but I can never get it locally. 

```
com.tns.NativeScriptException: Cannot find runtime for instance=com.tns.gen.okhttp3.Callback

com.tns.Runtime.callJSMethod Runtime.java:1157
com.tns.Runtime.callJSMethod Runtime.java:1138
com.tns.Runtime.callJSMethod Runtime.java:1134
com.tns.gen.okhttp3.Callback.onResponse Callback.java:26
okhttp3.RealCall$AsyncCall.execute RealCall.java:174
okhttp3.internal.NamedRunnable.run NamedRunnable.java:32
java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1167
```

This usually happens after at least 5 hours running, sometimes days running.

Any ideas?

Thanks,
Liam

**Comment by jerbob92** [comment]
Hi :)

Are you sure you are using this plugin? `com.tns.gen.okhttp3.Callback` doesn't sound like something we are executing from our plugin. We don't really do anything with okhttp callbacks from javascript. 

It sounds like you are using `nativescript-https`

**Comment by LiamMcCallum** [comment]
You're right, apologies for the inconvenience. Looks like we used to use `nativescript-https` in previous builds before upgrading to this plugin. Thanks for the fast reply!
