### ISSUE TITLE
Why not suggest a custom webpack configuration?

### ISSUE THREAD

**Issue by StephenCarboni** [klippa-app/nativescript-http#21]
According to the [docs](https://v7.docs.nativescript.org/tooling/custom-webpack-configuration), one should be able to just do this:

```javascript
// my-custom.webpack.config.js
const webpackConfig = require("./webpack.config");
const NativeScriptHTTPPlugin = require("@klippa/nativescript-http/webpack");

module.exports = (env) => {
  const config = webpackConfig(env);
  config.plugins.push(new NativeScriptHTTPPlugin());
  return config;
};
```

And in `nativescript.config.ts`, set `webpackConfigPath` to `"./my-custom.webpack.config.js"`

No more hassling with the stock webpack config anymore.

**Comment by jerbob92** [comment]
That's cool, didn't know that was possible :) I'll add it to the docs soon for the versions that support it.

**Comment by jerbob92** [comment]
Added this to the readme, thanks!
